### ISSUE TITLE
Implementation of a non-blocking linked list

### ISSUE THREAD

**Issue by lbrndnr** [glessard/swift-atomics#27]
I'm trying to implement a non-blocking linked list using your package but I'm having issues using the AtomicPointer struct. Maybe I missed something but I figured you could help me either way :)

Anyways, the function that appends a new element to the list looks as follows:
```swift
    func append(_ value: V) {
        let newTail = Element(value: value)
        
        withUnsafePointer(newTail) {
            var tail = head
            repeat {
                tail = head
                while tail.pointer != nil {
                    tail = tail.pointer!.pointee.next
                }
            } while !tail.CAS(current: nil, future: newTailPointer)
        }
    }
```

The problem I encounter is that since AtomicPointer is a struct, the while loop does not work as expected. When CASing the newTailPointer, is copied instead of referenced. Thus, the changes are not retained after the termination of this method.
Am I using your library wrong? Do you have any hints how it would be possible to implement a linked list using your atomic library? 

Thank you very much for your help :)

**Comment by lbrndnr** [comment]
2' later I saw your queues repo which answers all my questions :P thanks anyways

**Comment by glessard** [comment]
Glad it helps. Non-blocking linked lists are hard in Swift because of the extra level of memory handling required by ARC. I've been satisfied when the values passed around don't do any ARC, but I'd like to see an implementation that works well in every case!

**Comment by lbrndnr** [comment]
Will let you know if i come up with something interesting :) May I ask what tri-state memory in the comments of your queue library refers to?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glessard** [comment]
Refers to ARC with respect to UnsafePointer. In C or with an ARC-less struct, your memory is either allocated or not. With a struct that uses ARC, your memory can be unallocated, allocated, or (allocated and initialized); that's an extra state. During the dequeuing operation of the Michael-Scott algorithm, this extra state leads to use-after-free errors that I didn't manage to resolve -- though I didn't try tremendously hard. It's possible to resolve it by simply storing a pointer to whatever you're enqueuing, since the pointer itself is not active in ARC.

Note that if what you really need is only a non-blocking enqueue, you might be able to solve it more simply. I recently realized that situation (non-blocking-enqueue, serial dequeue) is a pretty common case, but I haven't done anything about it.

**Comment by lbrndnr** [comment]
Cool, thank you very much for the clarification :) Yes, I figured it would be easy to implement an efficient non-blocking queue for my use case but it proofed to be a bit more difficult than expected, as it often does.

**Comment by glessard** [comment]
For what it's worth, I added a multiple-producer, single-consumer wait-free queue to that collection of queues. It has a better throughput than all the multiple-producer-multiple-consumer queues I've attempted to implement, and works fine with references and structs that use ARC. MPSC happens to be what I needed this week, so yay.

**Comment by lbrndnr** [comment]
Cool, I‘ll have a look :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lbrndnr** [comment]
Would you mind explaining to me why the AtomicReference struct is not able to CAS? :)

**Comment by glessard** [comment]
Once the reference is known by another thread, that other thread could decrease the reference count to zero. If two threads know about a reference (via Unmanaged) whose reference count is 1, then either can lower the ref-count to 0 and trigger deinitialization. Then the other thread has no way of knowing that its reference is supposed to be dead, will try to use it and get a runtime error.

This is why I only implemented swap/exchange. There might be situations where your reference has its lifetime managed elsewhere so that CAS is viable, but that's not the general case. In CAtomicsTests/CAtomicsReferenceTests.testDemonstrateWhyLockIsNecessary, there's a step-by-step example of a reference whose count goes to zero in a way that would not be detectable across threads.

**Comment by lbrndnr** [comment]
Aahh I see, thanks for your reply :)

**Comment by lbrndnr** [comment]
Wouldn't it be possible to solve this problem by retaining the reference returned from a load? This will guarantee that the reference is not being freed while a thread uses it but it's still possible to release it from another thread by setting it to nil.
I don't know if this would require a major redesign though...

**Comment by glessard** [comment]
I wrote a long reply that didn't answer your comment, and then went back to answering your question from 2 days ago:

If you have a live reference and you try to use it for a CAS, it is true that it won't disappear from under you because you are already ensuring its liveness. It shouldn't return the current value of the reference in the failing case, though. If you want to propose an implementation and a test, I'll gladly take them.
